### ISSUE TITLE
Add {CRN}: {CroNode}

### ISSUE THREAD

**Issue by ghost** [cronaswap/default-token-list#1]
- [X] I understand that token listing is not required to use the CronaSwap Interface with a token.
- [X] I understand that filing an issue or adding liquidity does not guarantee addition to the CronaSwap default token list.
- [X] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address (checkSum): 0x8174BaC1453c3AC7CaED909c20ceaDeb5E1CDA00
Token Name (from contract): CroNode
Token Symbol (from contract): CRN
Token Decimals (from contract): 18
CronaSwap Pair Address of Token: 0x3Ca50D07B1cfb4a4e61EE8d00c2eF1af6E42CEE8

Link to official Twitter account: https://twitter.com/CronodesFinance
Link to the official homepage of token: https://www.cronodes.xyz/
Link to Token Logo (102x102 PNG, Circular logo): https://ibb.co/9VRhx3B
Link to CoinMarketCap or CoinGecko page of token (If any): (Coin Marketcap: https://coinmarketcap.com/currencies/cronodes/)
(Coin Gecko: https://www.coingecko.com/en/coins/cronodes)

**Comment by 0xHerzen** [comment]
Added

**Comment by ghost** [comment]
How long does that take to update roughly? I searched for it and I didn't see it there. @CronaChef 

Thanks again!
