### ISSUE TITLE
Add V3S: V3SToken

### ISSUE THREAD

**Issue by v3s-finance** [cronaswap/default-token-list#10]
- [x] I understand that token listing is not required to use the CronaSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the CronaSwap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address (checkSum): 0xC7e99a2f064Cf86aF91Db252a9D8Bc16e6fE7427
Token Name (from contract): V3SToken
Token Symbol (from contract): V3S
Token Decimals (from contract): 18
CronaSwap Pair Address of Token: 0x683Fac6A52c2b6256EC2118B6F2f20cf9048C8BE

Link to official Twitter account: https://twitter.com/v3sfinance
Link to the official homepage of token: https://www.v3s.finance/
Link to Token Logo (102x102 PNG, Circular logo): https://www.v3s.finance/images/v3s.png
Link to CoinMarketCap or CoinGecko page of token (If any):

**Comment by 0xHerzen** [comment]
Added, wait update!
