### ISSUE TITLE
Add VSHARE: VSHARE

### ISSUE THREAD

**Issue by v3s-finance** [cronaswap/default-token-list#11]
- [x] I understand that token listing is not required to use the CronaSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the CronaSwap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address (checkSum): 0xdcC261c03cD2f33eBea404318Cdc1D9f8b78e1AD
Token Name (from contract): VSHARE
Token Symbol (from contract): VSHARE
Token Decimals (from contract): 18
CronaSwap Pair Address of Token: 0x2622641900Bd6AB8062E2F0507C838610e5AA0d8

Link to official Twitter account: https://twitter.com/v3sfinance
Link to the official homepage of token: https://www.v3s.finance/
Link to Token Logo (102x102 PNG, Circular logo): https://www.v3s.finance/images/vshare.png
Link to CoinMarketCap or CoinGecko page of token (If any):

**Comment by 0xHerzen** [comment]
Added, wait update!
