### ISSUE TITLE
Add V3TONIC: V3S-Peg Tectonic

### ISSUE THREAD

**Issue by v3s-finance** [cronaswap/default-token-list#12]
- [x] I understand that token listing is not required to use the CronaSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the CronaSwap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address (checkSum): 0xA29EB0318F522ca98FdB5cEdc0c7549526625517
Token Name (from contract): V3S-Peg Tectonic
Token Symbol (from contract): V3TONIC
Token Decimals (from contract): 18
CronaSwap Pair Address of Token: 0x173F819F6596334d316A4DCcfe370DF375e7f9A3

Link to official Twitter account: https://twitter.com/v3sfinance
Link to the official homepage of token: https://www.v3s.finance/
Link to Token Logo (102x102 PNG, Circular logo): https://www.v3s.finance/images/v3tonic.png
Link to CoinMarketCap or CoinGecko page of token (If any):

**Comment by 0xHerzen** [comment]
added
