### ISSUE TITLE
Add {BASE}: {Defido Coin}

### ISSUE THREAD

**Issue by defido** [cronaswap/default-token-list#14]
- [x] I understand that token listing is not required to use the CronaSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the CronaSwap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address (checkSum): https://cronoscan.com/token/0x0422b63182798ae9876cae3cabd225d96b284d14
Token Name (from contract): Defido Coin
Token Symbol (from contract): BASE
Token Decimals (from contract): 18 
CronaSwap Pair Address of Token: https://cronoscan.com/token/0x7c8f28f3412035123691aa0bfbd128e902d09e7e

Link to official Twitter account: https://twitter.com/defido
Link to the official homepage of token: defido.com
Link to Token Logo (102x102 PNG, Circular logo): https://i.imgur.com/FWZD4p2.png
Link to CoinMarketCap or CoinGecko page of token (If any):

**Comment by 0xHerzen** [comment]
added!

**Comment by defido** [comment]
<3
