### ISSUE TITLE
Add {TOKEN_SYMBOL}: {TOKEN_NAME}

### ISSUE THREAD

**Issue by ghost** [cronaswap/default-token-list#16]
- [ x] I understand that token listing is not required to use the CronaSwap Interface with a token.
- [ x] I understand that filing an issue or adding liquidity does not guarantee addition to the CronaSwap default token list.
- [ x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address (checkSum): 0x6eDd4e7A5bd9688AAb374E5A0447c2A2FF10fAEA
Token Name (from contract): CroNodes Finance
Token Symbol (from contract): CRNF
Token Decimals (from contract): 18
CronaSwap Pair Address of Token: 0x2434a4E60FB702C909E11cc306A9Ad29fC16DBFd 

Link to official Twitter account: https://twitter.com/CronodesFinance
Link to the official homepage of token: https://cronodes.finance
Link to Token Logo (102x102 PNG, Circular logo): https://ibb.co/hDL3Tr9
Link to CoinMarketCap or CoinGecko page of token (If any):

**Comment by 0xHerzen** [comment]
Added.
