### ISSUE TITLE
Add {CORGI}: {Corgi}

### ISSUE THREAD

**Issue by ap408** [cronaswap/default-token-list#2]
- [x] I understand that token listing is not required to use the CronaSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the CronaSwap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address (checkSum): 0xcc6e924721f75af3a8f8282216569276f3f2a104
Token Name (from contract): Corgi
Token Symbol (from contract): CORGI
Token Decimals (from contract): 9
CronaSwap Pair Address of Token: 0xafcad2fa6ed56c7e3e8994f9d96b7cd4e625c599

Link to official Twitter account: https://twitter.com/CronosCorgi
Link to the official homepage of token: https://www.corgitoken.info/
Link to Token Logo (102x102 PNG, Circular logo): https://ibb.co/ykzQ2hg
Link to CoinMarketCap or CoinGecko page of token (If any): None

**Comment by 0xHerzen** [comment]
Added, wait our dev update!
