### ISSUE TITLE
Add {STC}: {Shitcoin}

### ISSUE THREAD

**Issue by Shit-toshi** [cronaswap/default-token-list#3]
- [Y] I understand that token listing is not required to use the CronaSwap Interface with a token.  
- [Y] I understand that filing an issue or adding liquidity does not guarantee addition to the CronaSwap default token list.  
- [Y] I will not ping the Discord about this listing request.  
  
**Please provide the following information for your token.**  
  
Token Address (checkSum): 0x28d82c4d7315c02d19562db1080a713eb5cc2639   
Token Name (from contract): Shitcoin  
Token Symbol (from contract): STC   
Token Decimals (from contract): 8  
CronaSwap Pair Address of Token: https://app.cronaswap.org/swap?   outputCurrency=0x28d82c4d7315c02d19562db1080a713eb5cc2639  

Link to official Twitter account: https://twitter.com/shitcoin69  
Link to the official homepage of token: https://shitcoin69.com/  
Link to Token Logo (102x102 PNG, Circular logo): https://i.ibb.co/gMJS7Ld/Shitcoin-Logo-102x102.png  
Link to CoinMarketCap or CoinGecko page of token (If any): https://coinmarketcap.com/currencies/shitcoin/

**Comment by 0xHerzen** [comment]
Hey, sir, 0x28d82c4d7315c02d19562db1080a713eb5cc2639 is not a token contract address?!
