### ISSUE TITLE
Add {ElonHype}: {ElonHype}

### ISSUE THREAD

**Issue by ElonhypeToken** [cronaswap/default-token-list#5]
- [x] I understand that token listing is not required to use the CronaSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the CronaSwap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address (checkSum):https://bscscan.com/token/0x7730ac665114c0e343b141daaaeb097197191f8a
Token Name (from contract):ElonHype
Token Symbol (from contract):ElonHype
Token Decimals (from contract):18
CronaSwap Pair Address of Token:0x559d816B3e938A73f5c6dBa2F69E7EF3e1ee67F4

Link to official Twitter account: https://twitter.com/ElonHypeToken
Link to the official homepage of token: https://elonhype.space/
Link to Token Logo (102x102 PNG, Circular logo):https://ibb.co/2thScbC
Link to CoinMarketCap or CoinGecko page of token (If any):

**Comment by 0xHerzen** [comment]
Hello, did you deployed on cronos chain now?
 CronaSwap Pair Address of Token:0x559d816B3e938A73f5c6dBa2F69E7EF3e1ee67F4

i can't found it.

**Comment by ElonhypeToken** [comment]
Hello
We are on Pancakeswap and Tokpie now

Вс, 13 февр. 2022 г. в 18:50, CronaChef ***@***.***>:

**Comment by 0xHerzen** [comment]
when you added into Cronos Chain!
we will listing
