### ISSUE TITLE
Add {BANK}: {CROBANK}

### ISSUE THREAD

**Issue by crobanker** [cronaswap/default-token-list#6]
- [x] I understand that token listing is not required to use the CronaSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the CronaSwap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address (checkSum): 0x55210C2a69b4c52a9d9289A257D54d35C4a2d2eC
Token Name (from contract): CroBank
Token Symbol (from contract): BANK
Token Decimals (from contract): 9
CronaSwap Pair Address of Token: 0xe6278a9425fc3ECc3514cD782598493043B6CDF4

Link to official Twitter account: https://twitter.com/cro_bank
Link to the official homepage of token: https://www.crobank.xyz
Link to Token Logo (102x102 PNG, Circular logo): https://ibb.co/SNsW8k1
Link to CoinMarketCap or CoinGecko page of token (If any): Nil

**Comment by 0xHerzen** [comment]
why not see your token contract?
https://cronoscan.com/address/0x55210C2a69b4c52a9d9289A257D54d35C4a2d2eC#code

**Comment by crobanker** [comment]
Contract unable to be verified for some reason on cronoscan, keep getting
an error

Try this old explorer:
https://cronos.crypto.org/explorer/address/0x55210C2a69b4c52a9d9289A257D54d35C4a2d2eC/contracts

**Comment by 0xHerzen** [comment]
added. wait update
