### ISSUE TITLE
Add CroATOM: CroATOM

### ISSUE THREAD

**Issue by ghost** [cronaswap/default-token-list#7]
- [ x] I understand that token listing is not required to use the CronaSwap Interface with a token.
- [ x] I understand that filing an issue or adding liquidity does not guarantee addition to the CronaSwap default token list.
- [ x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address (checkSum): 0x8b0D1164e98DD0592598B56C1Baa86462c73A2d1
Token Name (from contract): CroATOM
Token Symbol (from contract): CroATOM
Token Decimals (from contract): 9
CronaSwap Pair Address of Token: 0x9eb3062Fc6e52eb1aE17B7da2764aaCaebc5f025

Link to official Twitter account: https://twitter.com/cro_atom
Link to the official homepage of token: https://www.croatom.money/
Link to Token Logo (102x102 PNG, Circular logo): https://i.imgur.com/2Q3fN8f.png
Link to CoinMarketCap or CoinGecko page of token (If any): N/A

**Comment by 0xHerzen** [comment]
Added, pls check!
