### ISSUE TITLE
Add KAGU: KAGUNI

### ISSUE THREAD

**Issue by KaguniToken** [cronaswap/default-token-list#8]
- [x] I understand that token listing is not required to use the CronaSwap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the CronaSwap default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Token Address (checkSum):  0xB73b49aAb0B354A7868f9AD36c7a6AC357E20492
Token Name (from contract): Kaguni
Token Symbol (from contract): Kagu
Token Decimals (from contract): 18
CronaSwap Pair Address of Token: https://cronoscan.com/address/0x10EF542b89ed3df0FCd34a779269C102FC788f46

Link to official Twitter account: https://twitter.com/KaguniToken
Link to the official homepage of token: https://kaguni.com/
Link to Token Logo (102x102 PNG, Circular logo): https://ibb.co/pwhQrK6
Link to CoinMarketCap or CoinGecko page of token (If any):

**Comment by 0xHerzen** [comment]
OK, got it! Our dev will be update it.

**Comment by 0xHerzen** [comment]
![image](https://user-images.githubusercontent.com/91788983/156117256-56618e92-3fbf-48d9-b06a-6ddcef4ee73e.png)

The logo is not very clear. It would be better to provide a bright tone.

**Comment by KaguniToken** [comment]
Hello,
Is this one better? 
https://ibb.co/3C4BPhH

**Comment by 0xHerzen** [comment]
![image](https://user-images.githubusercontent.com/91788983/156182265-718cbe91-26f4-4d12-8434-e31f7ff86ac5.png)
Yes is good!

let us update to server!
